USE [master]
GO

/****** Object:  Database [Rithms]    Script Date: 22/02/2021 1:18:01 ******/
CREATE DATABASE [Rithms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Rithms', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Rithms.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Rithms_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Rithms_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Rithms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Rithms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Rithms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Rithms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Rithms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Rithms] SET ARITHABORT OFF 
GO

ALTER DATABASE [Rithms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Rithms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Rithms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Rithms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Rithms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Rithms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Rithms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Rithms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Rithms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Rithms] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Rithms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Rithms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Rithms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Rithms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Rithms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Rithms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Rithms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Rithms] SET RECOVERY FULL 
GO

ALTER DATABASE [Rithms] SET  MULTI_USER 
GO

ALTER DATABASE [Rithms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Rithms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Rithms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Rithms] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Rithms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Rithms] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Rithms] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Rithms] SET  READ_WRITE 
GO

